// ─── Scaffold Templates ────────────────────────────────────────────────────────
//
// All templates are pure functions that accept ScaffoldOptions and return
// the file content as a string. No file I/O occurs here.

import type { ScaffoldOptions, ScaffoldFile } from "./types.js";

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/** Derives the plugin id (camelCase) from the package name. */
export function pluginId(opts: ScaffoldOptions): string {
  // Strip scope if present: "@acme/ficecal-plugin-foo" → "ficecal-plugin-foo"
  const base = opts.packageName.includes("/")
    ? opts.packageName.split("/")[1]!
    : opts.packageName;
  // kebab-case → camelCase
  return base.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/** Derives the directory name from the package name (last segment, no scope). */
export function dirName(packageName: string): string {
  return packageName.includes("/") ? packageName.split("/")[1]! : packageName;
}

// ---------------------------------------------------------------------------
// Shared files (always generated)
// ---------------------------------------------------------------------------

export function packageJsonTemplate(opts: ScaffoldOptions): string {
  return JSON.stringify(
    {
      name: opts.packageName,
      version: "0.1.0",
      description: opts.description,
      type: "module",
      main: "./src/index.ts",
      exports: { ".": "./src/index.ts" },
      scripts: {
        build: "tsc",
        typecheck: "tsc --noEmit",
        test: "vitest run",
      },
      peerDependencies: {
        "@ficecal/plugin-api": ">=2.0.0",
      },
      devDependencies: {
        "@ficecal/plugin-api": "workspace:*",
        typescript: "~5.4.5",
        vitest: "^2.0.0",
      },
      keywords: ["ficecal", "ficecal-plugin"],
      author: opts.author,
      license: opts.license,
    },
    null,
    2
  );
}

export function tsconfigTemplate(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "bundler",
        lib: ["ES2022"],
        strict: true,
        noImplicitReturns: true,
        skipLibCheck: true,
        noEmit: true,
        allowImportingTsExtensions: true,
      },
      include: ["src/**/*", "tests/**/*"],
    },
    null,
    2
  );
}

export function readmeTemplate(opts: ScaffoldOptions): string {
  return `# ${opts.displayName}

> ${opts.description}

A [FiceCal v2](https://github.com/duksh/FiceCal) community plugin.

## Installation

\`\`\`bash
pnpm add ${opts.packageName}
\`\`\`

## Usage

\`\`\`ts
import { plugin } from "${opts.packageName}";
import { PluginHost } from "@ficecal/plugin-api";

const host = new PluginHost(mcpRegistrar, []);
host.register(plugin);
\`\`\`

## Development

\`\`\`bash
pnpm install
pnpm typecheck
pnpm test
\`\`\`

## License

${opts.license}
`;
}

// ---------------------------------------------------------------------------
// src/index.ts — varies by plugin type
// ---------------------------------------------------------------------------

export function indexTemplate(opts: ScaffoldOptions): string {
  const id = pluginId(opts);
  const parts: string[] = [];

  parts.push(`// ─── ${opts.displayName} ─────────────────────────────────────────────────────`);
  parts.push(`//`);
  parts.push(`// FiceCal v2 community plugin.`);
  parts.push(`// Generated by create-ficecal-plugin.`);
  parts.push(``);
  parts.push(`import type { FicecalPlugin } from "@ficecal/plugin-api";`);

  if (opts.pluginType === "billing" || opts.pluginType === "full") {
    parts.push(`import { billingAdapterContribution } from "./billing-adapter.js";`);
  }
  if (opts.pluginType === "theme" || opts.pluginType === "full") {
    parts.push(`import { themeContribution } from "./theme.js";`);
  }
  if (opts.pluginType === "mcp" || opts.pluginType === "full") {
    parts.push(`import { mcpToolContribution } from "./mcp-tool.js";`);
  }

  parts.push(``);
  parts.push(`export const plugin: FicecalPlugin = {`);
  parts.push(`  id: "${opts.packageName}",`);
  parts.push(`  name: "${opts.displayName}",`);
  parts.push(`  version: "0.1.0",`);
  parts.push(`  description: "${opts.description}",`);
  parts.push(`  author: "${opts.author}",`);
  parts.push(`  license: "${opts.license}",`);

  // contributions
  const contributions: string[] = [];
  if (opts.pluginType === "billing" || opts.pluginType === "full") {
    contributions.push(`    billingAdapters: [billingAdapterContribution],`);
  }
  if (opts.pluginType === "theme" || opts.pluginType === "full") {
    contributions.push(`    themes: [themeContribution],`);
  }
  if (opts.pluginType === "mcp" || opts.pluginType === "full") {
    contributions.push(`    mcpTools: [mcpToolContribution],`);
  }

  if (contributions.length > 0) {
    parts.push(`  contributions: {`);
    parts.push(...contributions);
    parts.push(`  },`);
  } else {
    parts.push(`  contributions: {},`);
  }

  parts.push(`};`);
  parts.push(``);
  parts.push(`export default plugin;`);

  return parts.join("\n");
}

// ---------------------------------------------------------------------------
// Type-specific contribution files
// ---------------------------------------------------------------------------

export function billingAdapterTemplate(opts: ScaffoldOptions): string {
  return `// ─── Billing Adapter Contribution ────────────────────────────────────────────
//
// Replace the stub load() implementation with your actual API calls.

import type { BillingAdapterContribution } from "@ficecal/plugin-api";

export const billingAdapterContribution: BillingAdapterContribution = {
  provider: "custom",   // ← change to your provider name (e.g. "datadog")
  ingestMode: "deterministic",

  fixture: {
    version: "1.0.0",
    data: {
      provider: "custom",
      billingPeriodStart: "2026-01-01",
      billingPeriodEnd: "2026-02-01",
      totalCost: 0,
      currency: "USD",
      lineItems: [],
    },
  },

  adapter: {
    ingestMode: "deterministic",

    async load(periodStart: string, periodEnd: string): Promise<unknown> {
      // TODO: replace with real API call
      // Example: call your vendor's billing API for the given period
      return {
        provider: "custom",
        billingPeriodStart: periodStart,
        billingPeriodEnd: periodEnd,
        totalCost: 0,
        currency: "USD",
        lineItems: [],
      };
    },
  },
};
`;
}

export function themeTemplate(opts: ScaffoldOptions): string {
  const id = pluginId(opts);
  return `// ─── Theme Contribution ───────────────────────────────────────────────────────

import type { ThemeContribution } from "@ficecal/plugin-api";

export const themeContribution: ThemeContribution = {
  id: "${id}-theme",
  name: "${opts.displayName} Theme",
  description: "Custom theme contributed by ${opts.displayName}",
  tokens: {
    // ─── Color tokens ─────────────────────────────────────────────────────────
    "--color-primary":        "#6366f1",
    "--color-primary-hover":  "#4f46e5",
    "--color-surface":        "#ffffff",
    "--color-surface-raised": "#f8fafc",
    "--color-border":         "#e2e8f0",
    "--color-text":           "#0f172a",
    "--color-text-muted":     "#64748b",
    "--color-accent":         "#06b6d4",

    // ─── Typography ───────────────────────────────────────────────────────────
    "--font-sans": "'Inter Variable', system-ui, sans-serif",
    "--font-mono": "'JetBrains Mono', monospace",

    // ─── Spacing / radius ─────────────────────────────────────────────────────
    "--radius-sm": "4px",
    "--radius-md": "8px",
    "--radius-lg": "12px",
  },
};
`;
}

export function mcpToolTemplate(opts: ScaffoldOptions): string {
  const id = pluginId(opts);
  const toolId = opts.packageName.replace(/^@[^/]+\/ficecal-plugin-/, "").replace(/-/g, ".");
  return `// ─── MCP Tool Contribution ────────────────────────────────────────────────────
//
// Replace the stub handler with your real tool implementation.

import type { McpToolContribution } from "@ficecal/plugin-api";

export const mcpToolContribution: McpToolContribution = {
  tool: {
    id: "${toolId}.query",
    name: "${opts.displayName} Query",
    description: "Queries data from ${opts.displayName}.",
    namespace: "${toolId}",
    stability: "experimental",

    inputSchema: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "The query to execute.",
        },
      },
      required: ["query"],
    },

    handler: async (envelope) => {
      const { input, context } = envelope;
      const { query } = input as { query: string };

      // TODO: implement real handler
      return {
        toolId: "${toolId}.query",
        executedAt: new Date().toISOString(),
        requestId: context.requestId,
        output: {
          result: \`Stub result for query: \${query}\`,
        },
        warnings: ["This is a stub handler — implement real logic in src/mcp-tool.ts"],
        appliedIds: [],
      };
    },
  },
};
`;
}

// ---------------------------------------------------------------------------
// Test file template
// ---------------------------------------------------------------------------

export function testTemplate(opts: ScaffoldOptions): string {
  return `// ─── ${opts.displayName} — Plugin Tests ────────────────────────────────────
//
// Replace these placeholder tests with real assertions.

import { describe, it, expect } from "vitest";
import { plugin } from "../src/index.js";

describe("${opts.packageName}", () => {
  it("has correct id", () => {
    expect(plugin.id).toBe("${opts.packageName}");
  });

  it("has non-empty name", () => {
    expect(plugin.name.length).toBeGreaterThan(0);
  });

  it("has non-empty version", () => {
    expect(plugin.version).toBeDefined();
  });

  it("has contributions object", () => {
    expect(plugin.contributions).toBeDefined();
  });
});
`;
}

// ---------------------------------------------------------------------------
// Main scaffold builder — assembles all files for the given options
// ---------------------------------------------------------------------------

/**
 * Returns the complete list of files to scaffold for the given options.
 * Pure function — no file I/O.
 */
export function buildScaffoldFiles(opts: ScaffoldOptions): ScaffoldFile[] {
  const files: ScaffoldFile[] = [
    { path: "package.json",     content: packageJsonTemplate(opts) },
    { path: "tsconfig.json",    content: tsconfigTemplate() },
    { path: "README.md",        content: readmeTemplate(opts) },
    { path: "src/index.ts",     content: indexTemplate(opts) },
    { path: "tests/plugin.test.ts", content: testTemplate(opts) },
  ];

  if (opts.pluginType === "billing" || opts.pluginType === "full") {
    files.push({ path: "src/billing-adapter.ts", content: billingAdapterTemplate(opts) });
  }

  if (opts.pluginType === "theme" || opts.pluginType === "full") {
    files.push({ path: "src/theme.ts", content: themeTemplate(opts) });
  }

  if (opts.pluginType === "mcp" || opts.pluginType === "full") {
    files.push({ path: "src/mcp-tool.ts", content: mcpToolTemplate(opts) });
  }

  return files;
}
